# Generated by Django 5.2.7 on 2025-12-29 12:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pesel', models.CharField(max_length=11, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatientResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('survey_id', models.CharField(max_length=100)),
                ('question_id', models.CharField(max_length=100)),
                ('response_type', models.CharField(choices=[('scale', 'Scale 1-10'), ('text', 'Text'), ('audio', 'Audio')], max_length=10)),
                ('scale_value', models.FloatField(blank=True, null=True)),
                ('text_answer', models.TextField(blank=True, null=True)),
                ('question_text', models.TextField(blank=True, null=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='audio_answers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transcript', models.TextField(blank=True)),
                ('evaluated_score', models.FloatField(blank=True, null=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='cantrilapp.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('order', models.PositiveIntegerField()),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='cantrilapp.survey')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
