# Generated by Django 5.2.2 on 2025-06-08 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pesel', models.CharField(max_length=11)),
                ('score', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('context', models.CharField(choices=[('admission', 'Przyjęcie'), ('discharge', 'Wypis'), ('followup', 'Follow-up')], max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_synced_with_his', models.BooleanField(default=False)),
            ],
        ),
    ]
