# Generated by Django 5.2.9 on 2025-12-30 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cantrilapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='scale_labels',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='survey',
            name='ladder_design',
            field=models.CharField(choices=[('classic', 'Klasyczny - Niebieski gradient'), ('gradient', 'Gradient - Dynamiczny'), ('minimal', 'Minimalistyczny - Prosty'), ('circular', 'Okrągły - Nowoczesny'), ('modern', 'Nowoczesny - Śmiały')], default='classic', max_length=20),
        ),
    ]
