# Generated by assistant - migration to add Question model and question FK
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('cantrilapp', '0002_patient_remove_patientresponse_pesel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='patientresponse',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_responses', to='cantrilapp.question'),
        ),
        migrations.AlterField(
            model_name='patientresponse',
            name='context',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
