# Generated by Django 5.2.9 on 2025-12-30 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cantrilapp', '0002_question_scale_labels_survey_ladder_design'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientresponse',
            name='survey_id',
        ),
        migrations.AddField(
            model_name='patientresponse',
            name='json_survey_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patientresponse',
            name='survey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='cantrilapp.survey'),
        ),
    ]
